# Generated by Django 5.2 on 2025-05-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_alter_userprofile_address_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeapp.branch'),
        ),
    ]
