# Generated by Django 5.2 on 2025-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_sale_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_manager_2',
            field=models.BooleanField(default=False),
        ),
    ]
